services:
  - type: web
    name: rag-game-assistant-backend
    env: python
    buildCommand: cd backend && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --config gunicorn_config.py "app.main:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_DEBUG
        value: false
      - key: ENABLE_CACHE
        value: true
      - key: CACHE_DIR
        value: /opt/render/project/src/backend/.cache
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
      # Reduce batch sizes and limits
      - key: VECTOR_STORE_TOP_K
        value: "4"
      - key: LLM_MAX_TOKENS
        value: "2048"
      - key: CHUNK_SIZE
        value: "1000"
      - key: CHUNK_OVERLAP
        value: "100"
    healthCheckPath: /api/
    autoDeploy: true

  - type: web
    name: rag-game-assistant-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://rag-game-assistant.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache