services:
  - type: web
    name: rag-game-assistant
    env: python
    region: oregon  # Choose your preferred region
    plan: starter  # Adjust based on your needs
    buildCommand: |
      python -m pip install --upgrade pip
      cd backend
      pip install -r requirements.txt
      python deployment_test.py
    startCommand: >
      cd backend && gunicorn app.main:create_app() 
      --timeout 180 
      --workers 2 
      --threads 4 
      --worker-class gthread 
      --log-level info 
      --bind 0.0.0.0:$PORT 
      --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_DEBUG
        value: false
      - key: ENABLE_CACHE
        value: true
      - key: CACHE_DIR
        value: /opt/render/project/src/backend/.cache
      - key: ANTHROPIC_API_KEY
        sync: false  # Mark as secret
      - key: COHERE_API_KEY
        sync: false  # Mark as secret
      - key: ALLOWED_ORIGIN
        sync: false  # Configure in Render dashboard
      - key: MAX_CHUNK_SIZE
        value: 4500
      - key: CHUNK_SIZE
        value: 2000
      - key: CHUNK_OVERLAP
        value: 200
      - key: VECTOR_STORE_SIMILARITY_THRESHOLD
        value: 0.3
      - key: VECTOR_STORE_TOP_K
        value: 8
      - key: LLM_TEMPERATURE
        value: 0.3
      - key: LLM_MAX_TOKENS
        value: 4096
      - key: MMR_DIVERSITY_SCORE
        value: 0.3
    healthCheckPath: /api/
    autoDeploy: false  # Set to false for controlled deployments
    disk:
      name: cache
      mountPath: /opt/render/project/src/backend/.cache
      sizeGB: 1

  - type: web
    name: rag-game-assistant-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://rag-game-assistant.onrender.com # Change to your backend URL
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html