services:
  - type: web
    name: rag-game-assistant-backend
    env: python
    buildCommand: cd backend && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: >
      cd backend && gunicorn "app.main:create_app()" 
      --timeout 300 
      --workers 1
      --threads 4
      --worker-class gthread
      --log-level info
      --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_DEBUG
        value: false
      - key: ENABLE_CACHE
        value: true
      - key: CACHE_DIR
        value: /opt/render/project/src/backend/.cache
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
      - key: VECTOR_STORE_SIMILARITY_THRESHOLD
        value: "0.3"
      - key: VECTOR_STORE_TOP_K
        value: "8"
      - key: LLM_TEMPERATURE
        value: "0.3"
      - key: LLM_MAX_TOKENS
        value: "4096"
      - key: MMR_DIVERSITY_SCORE
        value: "0.3"
    healthCheckPath: /api/
    autoDeploy: true
    disk:
      name: cache
      mountPath: /opt/render/project/src/backend/.cache
      sizeGB: 1

  - type: web
    name: rag-game-assistant-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://rag-game-assistant.onrender.com # Change to your backend URL
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html