services:
  - type: web
    name: rag-game-assistant  # Change this to match your Render service name
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: cd backend && gunicorn "app.main:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1