services:
  - type: web
    name: rag-game-assistant-backend
    env: python
    buildCommand: cd backend && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --config gunicorn_config.py "app.main:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG 
        value: false
      - key: ENABLE_CACHE
        value: true
      - key: CACHE_DIR
        value: /opt/render/project/src/.cache
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false  
      - key: ALLOWED_ORIGIN
        value: "https://rag-game-assistant-frontend.onrender.com"
      - key: VECTOR_STORE_TOP_K
        value: "3"
      - key: LLM_MAX_TOKENS
        value: "512"  # Reduced token limit
      - key: CHUNK_SIZE
        value: "500"
      - key: CHUNK_OVERLAP
        value: "50"
      - key: WEB_CONCURRENCY
        value: "1"
    healthCheckPath: /api/
    autoDeploy: true

  - type: web
    name: rag-game-assistant-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://rag-game-assistant-backend.onrender.com"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache