services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: >
      cd backend && gunicorn "app.main:create_app()" 
      --timeout 120 
      --workers 2 
      --threads 4 
      --worker-class gthread
      --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: false
      - key: GUNICORN_TIMEOUT
        value: 120
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1